import { renderMarkdown } from './markdown.js';

const desc = {
  severityLevels: {
    low: '低危',
    moderate: '中危',
    high: '高危',
    critical: '严重',
  },
  severityLevelsEn: {
    low: 'Low',
    moderate: 'Moderate',
    high: 'High',
    critical: 'Critical',
  },
  translations: {
    auditResult: '审计结果',
    auditResultEn: 'Audit Result',
    detectionTarget: '检测目标',
    detectionTargetEn: 'Detection Target',
    linkAddress: '链接地址',
    linkAddressEn: 'Link Address',
    filePath: '文件路径',
    filePathEn: 'File Path',
    noVulnerabilities: '你项目的所有直接依赖和间接依赖都没有发现任何风险漏洞。',
    noVulnerabilitiesEn: 'No security vulnerabilities were found in your project\'s direct and indirect dependencies.',
    dependencyManagementRecommendations: '依赖管理建议',
    dependencyManagementRecommendationsEn: 'Dependency Management Recommendations',
    maintainCurrentStatus: '保持现状',
    maintainCurrentStatusEn: 'Maintain Current Status',
    projectStatusGood: '项目当前的依赖管理状况良好，没有发现任何风险漏洞',
    projectStatusGoodEn: 'The project\'s current dependency management status is good, with no security vulnerabilities found.',
    continueCurrentPractices: '建议继续保持当前的依赖管理实践',
    continueCurrentPracticesEn: 'It is recommended to continue with the current dependency management practices.',
    continuousImprovement: '持续改进',
    continuousImprovementEn: 'Continuous Improvement',
    regularAudits: '定期审计',
    regularAuditsEn: 'Regular Audits',
    monthlyAudits: '建议至少每月运行一次依赖审计，确保新发现的漏洞能够及时处理',
    monthlyAuditsEn: 'It is recommended to run dependency audits at least monthly to ensure timely handling of newly discovered vulnerabilities.',
    updateDependencies: '更新依赖',
    updateDependenciesEn: 'Update Dependencies',
    updateToLatestSecureVersions: '定期更新依赖到最新的安全版本',
    updateToLatestSecureVersionsEn: 'Regularly update dependencies to the latest secure versions.',
    monitorDependencies: '监控依赖',
    monitorDependenciesEn: 'Monitor Dependencies',
    useMonitoringTools: '考虑使用依赖监控工具，及时获取依赖的安全更新通知',
    useMonitoringToolsEn: 'Consider using dependency monitoring tools to receive timely notifications about security updates.',
    totalVulnerabilities: '您所审计的工程总共有',
    totalVulnerabilitiesEn: 'Your audited project has a total of',
    vulnerabilities: '个风险漏洞。',
    vulnerabilitiesEn: 'security vulnerabilities.',
    where: '其中：',
    whereEn: 'Where:',
    vulnerabilitiesDescription: '说明：',
    vulnerabilitiesDescriptionEn: 'Description:',
    criticalDescription: '漏洞被认为是极其严重的，应该立即修复。',
    criticalDescriptionEn: 'vulnerabilities are considered extremely severe and should be fixed immediately.',
    highDescription: '漏洞被认为是严重的，应该尽快修复。',
    highDescriptionEn: 'vulnerabilities are considered severe and should be fixed as soon as possible.',
    moderateDescription: '漏洞被认为是中等严重的，可以选择在时间允许时修复。',
    moderateDescriptionEn: 'vulnerabilities are considered moderately severe and can be fixed when time permits.',
    lowDescription: '漏洞被认为是轻微的，可以根据自行需要进行修复。',
    lowDescriptionEn: 'vulnerabilities are considered minor and can be fixed according to your own needs.',
    detailedInformation: '下面是漏洞的详细信息',
    detailedInformationEn: 'Below is the detailed information about the vulnerabilities',
    fixPriorityRecommendations: '修复优先级建议',
    fixPriorityRecommendationsEn: 'Fix Priority Recommendations',
    fixCriticalImmediately: '立即修复严重(Critical)漏洞',
    fixCriticalImmediatelyEn: 'Fix Critical Vulnerabilities Immediately',
    criticalImpact: '这些漏洞可能导致系统被完全控制或数据泄露',
    criticalImpactEn: 'These vulnerabilities may lead to complete system control or data leakage',
    fixCriticalWithin24h: '建议在24小时内修复所有严重漏洞',
    fixCriticalWithin24hEn: 'It is recommended to fix all critical vulnerabilities within 24 hours',
    fixHighAsSoonAsPossible: '尽快修复高危(High)漏洞',
    fixHighAsSoonAsPossibleEn: 'Fix High Vulnerabilities As Soon As Possible',
    highImpact: '这些漏洞可能导致重要功能被破坏或敏感信息泄露',
    highImpactEn: 'These vulnerabilities may lead to important functionality disruption or sensitive information leakage',
    fixHighWithin7d: '建议在7天内修复所有高危漏洞',
    fixHighWithin7dEn: 'It is recommended to fix all high vulnerabilities within 7 days',
    fixModeratePlanned: '计划修复中危(Moderate)漏洞',
    fixModeratePlannedEn: 'Plan to Fix Moderate Vulnerabilities',
    moderateImpact: '这些漏洞在特定条件下可能被利用',
    moderateImpactEn: 'These vulnerabilities may be exploited under specific conditions',
    fixModerateInNextRelease: '建议在下一个版本更新中修复所有中危漏洞',
    fixModerateInNextReleaseEn: 'It is recommended to fix all moderate vulnerabilities in the next version update',
    fixLowEvaluate: '评估修复低危(Low)漏洞',
    fixLowEvaluateEn: 'Evaluate Fixing Low Vulnerabilities',
    lowImpact: '这些漏洞通常影响较小',
    lowImpactEn: 'These vulnerabilities usually have minor impacts',
    fixLowBasedOnSituation: '建议根据项目实际情况评估是否需要修复',
    fixLowBasedOnSituationEn: 'It is recommended to evaluate whether to fix based on the actual project situation',
    dependencyVersionManagement: '依赖版本管理建议',
    dependencyVersionManagementEn: 'Dependency Version Management Recommendations',
    useFixedVersion: '使用固定版本号',
    useFixedVersionEn: 'Use Fixed Version Numbers',
    avoidTildeCaret: '避免在package.json中使用波浪号(~)或插入符号(^)指定版本',
    avoidTildeCaretEn: 'Avoid using tilde (~) or caret (^) in package.json to specify versions',
    useExactVersion: '使用精确版本号可以避免意外引入有漏洞的依赖版本',
    useExactVersionEn: 'Using exact version numbers can avoid accidentally introducing vulnerable dependency versions',
    updateDependenciesRegularly: '定期更新依赖',
    updateDependenciesRegularlyEn: 'Update Dependencies Regularly',
    useNpmOutdated: '使用`npm outdated`命令检查过时的依赖',
    useNpmOutdatedEn: 'Use the `npm outdated` command to check for outdated dependencies',
    useNcuTool: '考虑使用`npm-check-updates`或类似工具批量更新依赖',
    useNcuToolEn: 'Consider using `npm-check-updates` or similar tools to batch update dependencies',
    updateForSecurity: '定期更新依赖可以获取安全修复和性能改进',
    updateForSecurityEn: 'Regularly updating dependencies can obtain security fixes and performance improvements',
    removeUnusedDependencies: '移除未使用的依赖',
    removeUnusedDependenciesEn: 'Remove Unused Dependencies',
    checkAndRemove: '定期检查并移除项目中不再使用的依赖',
    checkAndRemoveEn: 'Regularly check and remove dependencies that are no longer used in the project',
    reduceDependencyCount: '减少依赖数量可以降低安全风险和项目复杂度',
    reduceDependencyCountEn: 'Reducing the number of dependencies can lower security risks and project complexity',
    useLockFiles: '使用依赖锁定文件',
    useLockFilesEn: 'Use Dependency Lock Files',
    includeLockFiles: '确保项目中包含package-lock.json或yarn.lock文件',
    includeLockFilesEn: 'Ensure that the project includes package-lock.json or yarn.lock files',
    lockFilesBenefit: '锁定文件可以确保团队成员和部署环境使用相同版本的依赖',
    lockFilesBenefitEn: 'Lock files can ensure that team members and deployment environments use the same dependency versions',
    securityAuditRecommendations: '安全审计建议',
    securityAuditRecommendationsEn: 'Security Audit Recommendations',
    integrateWithCicd: '集成到CI/CD流程',
    integrateWithCicdEn: 'Integrate with CI/CD Pipeline',
    integrateAuditIntoCicd: '将依赖审计集成到持续集成/持续部署流程中',
    integrateAuditIntoCicdEn: 'Integrate dependency audits into the continuous integration/continuous deployment pipeline',
    runAuditBeforeDeploy: '在代码提交或部署前自动运行依赖审计',
    runAuditBeforeDeployEn: 'Automatically run dependency audits before code submission or deployment',
    manualAuditsRegularly: '定期手动审计',
    manualAuditsRegularlyEn: 'Regular Manual Audits',
    runManualAudits: '即使依赖没有变化，也建议定期手动运行依赖审计',
    runManualAuditsEn: 'It is recommended to regularly run manual dependency audits even if dependencies have not changed',
    newVulnerabilitiesFound: '新的漏洞可能在依赖发布后被发现',
    newVulnerabilitiesFoundEn: 'New vulnerabilities may be discovered after dependencies are released',
    followSecurityAnnouncements: '关注安全公告',
    followSecurityAnnouncementsEn: 'Follow Security Announcements',
    followDependenciesUpdates: '关注常用依赖的安全公告和更新',
    followDependenciesUpdatesEn: 'Follow security announcements and updates for commonly used dependencies',
    useSecurityMonitoring: '考虑使用安全监控服务跟踪依赖的安全状态',
    useSecurityMonitoringEn: 'Consider using security monitoring services to track the security status of dependencies',
    vulnerabilityDescription: '漏洞描述',
    vulnerabilityDescriptionEn: 'Vulnerability Description',
    npmVulnerabilityId: 'npm漏洞编号',
    npmVulnerabilityIdEn: 'npm Vulnerability ID',
    vulnerabilityDetails: '漏洞详细说明',
    vulnerabilityDetailsEn: 'Vulnerability Details',
    vulnerabilitySeverity: '漏洞等级',
    vulnerabilitySeverityEn: 'Vulnerability Severity',
    affectedVersions: '受影响的版本',
    affectedVersionsEn: 'Affected Versions',
    dependencyRelationship: '依赖关系',
    dependencyRelationshipEn: 'Dependency Relationship',
    currentProject: '当前工程',
    currentProjectEn: 'Current Project',
    vulnerabilityPackageDirectory: '漏洞包所在目录',
    vulnerabilityPackageDirectoryEn: 'Vulnerability Package Directory',
    fixRecommendation: '修复建议',
    fixRecommendationEn: 'Fix Recommendation',
    updateToVersion: '将',
    updateToVersionEn: 'Update',
    toVersion: '更新到版本',
    toVersionEn: 'to version',
    noteSemverMajor: '注意：这是一个主版本升级，可能包含不兼容的更改',
    noteSemverMajorEn: 'Note: This is a major version upgrade and may contain incompatible changes',
    updateToLatestVersion: '将更新到最新版本',
    updateToLatestVersionEn: 'Update to the latest version',
    noAutoFixAvailable: '目前没有自动修复建议，请关注官方公告或社区解决方案',
    noAutoFixAvailableEn: 'No automatic fix recommendations are currently available. Please follow official announcements or community solutions',
  }
};

/**
 * 将auditResult渲染为markdown格式的字符串
 * @param {object} auditResult 规范化的审计结果
 * @param {object} packageJson 包的package.json内容
 * @param {string} targetPath 被检测的文件地址或链接路径
 */
export async function render(auditResult, packageJson, targetPath) {
  const data = {
    audit: auditResult,
    desc,
    packageJson,
    targetPath,
  };
  return await renderMarkdown(data);
}
